### ISSUE TITLE
ruamel.yaml > 0.15.51 breaks setup parsing

### ISSUE THREAD

**Issue by m-strasser** [moreonion/drupy#9]
If `ruamel.yaml > 0.15.51` is installed, parsing of setup files fails with: `TypeError: Object of type 'CommentedMap' is not JSON serializable`.

Steps to reproduce:
1. `pip3 install drupy`
2. `pip3 install --upgrade ruamel.yaml`
3. `drupy install mysetup`

This fails with all .yaml files, no matter if they're valid or not (even empty .yaml files produce the error).

Workaround:
`pip3 install ruamel.yaml==0.15.51`

**Comment by torotil** [comment]
Not upgrading ruamel.yaml is not a permanent solution though. So is there an upstream bug report that’s being worked on?
